# Generated by Django 4.1 on 2022-08-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akshayapp', '0002_das'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='das',
            new_name='Bike',
        ),
    ]
